# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b0329d9001f5b734d5afa0e574a336a3733c2d0fee3f38276ece0f7958f57f064e92b9498ec341772ec36b1173991d5a446604c77f6139d5ced1a24d72e9054

test:
  secret_key_base: 2f0fd6bf92bd8969ea569d713e75d71d67bc5988ea435bd68cb08d2caf446e9a08b8fa5681d6150411b8bbd76f8933cfb0844bff3a71cced971d51a5a834534b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
